=== kulnor/codata-drum/udunits/xml/CodataUnitSystem.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" vc:minVersion="1.1">
    <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="https://www.w3.org/2009/01/xml.xsd"/>
    <xs:element name="UnitSystem" type="UnitSystemType"/>
    <xs:complexType name="UnitSystemType" abstract="false">
        <xs:sequence>
            <xs:element name="Prefixes">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="Prefix" type="PrefixType"> </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Quantities">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="Quantity">
                            <xs:complexType>
                                <xs:complexContent>
                                    <xs:extension base="IdentifiableType">
                                        <xs:sequence>
                                            <xs:element ref="Name"/>
                                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="AlternateName"/>
                                            <xs:element maxOccurs="unbounded" minOccurs="0" ref="Definition"/>
                                        </xs:sequence>
                                    </xs:extension>
                                </xs:complexContent>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Units">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element maxOccurs="unbounded" minOccurs="0" name="Unit" type="UnitType"> </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Constants">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element minOccurs="0" name="Constant" type="ConstantType"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="AlternateName" type="NameType">
        <xs:annotation>
            <xs:documentation>An entity alternate name</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType abstract="false" name="AlternateNameType">
        <xs:complexContent>
            <xs:extension base="NameType">
                <xs:sequence>
                    <xs:element minOccurs="0" ref="Description"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="AlternateSymbolType">
        <xs:simpleContent>
            <xs:extension base="SymbolType"> </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="AlternateBase" type="BaseType">
        <xs:annotation>
            <xs:documentation>The Unit(s) this entity is derived from (does not need to be base SI units)
</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:element name="Base" type="BaseType">
        <xs:annotation>
            <xs:documentation>The Unit(s) this entity is derived from, expressed in SI base units</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType name="BaseType">
        <xs:sequence>
            <xs:element minOccurs="0" name="Expression"/>
            <xs:element maxOccurs="unbounded" name="BaseUnit">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="UnitRef" type="ReferenceType"/>
                        <xs:element name="Exponent" type="xs:int"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="ConstantType">
        <xs:complexContent>
            <xs:extension base="IdentifiableType">
                <xs:sequence>
                    <xs:element ref="Name"/>
                    <xs:element ref="Symbol"/>
                    <xs:element name="Value" type="xs:double"/>
                    <xs:element name="UnitRef" type="ReferenceType"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:element name="Definition" type="InternationalString"/>
    <xs:element name="Description" type="InternationalString"/>
    <xs:complexType abstract="true" name="IdentifiableType">
        <xs:attribute name="uri" type="xs:anyURI" use="required"/>
    </xs:complexType>
    <xs:complexType name="InternationalString">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute ref="xml:lang" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:element name="Name" type="NameType">
        <xs:annotation>
            <xs:documentation>The SI official name of the entity.</xs:documentation>
        </xs:annotation>
    </xs:element>
    <xs:complexType abstract="false" name="NameType">
        <xs:sequence>
            <xs:element name="Singular" maxOccurs="unbounded" type="InternationalString"/>
            <xs:element minOccurs="0" name="Plural" default="" maxOccurs="unbounded" type="InternationalString"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="Symbol" type="SymbolType"/>
    <xs:complexType name="SymbolType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute default="true" name="isSI" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="PrefixType">
        <xs:complexContent>
            <xs:extension base="IdentifiableType">
                <xs:sequence>
                    <xs:element ref="Name"/>
                    <xs:element ref="Symbol"/>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType abstract="false" name="ReferenceType">
        <xs:simpleContent>
            <xs:extension base="xs:string"/>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="UnitType">
        <xs:complexContent>
            <xs:extension base="IdentifiableType">
                <xs:sequence>
                    <xs:element ref="Name"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" ref="AlternateName"/>
                    <xs:element ref="Symbol"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="AlternateSymbol" type="AlternateSymbolType"/>
                    <xs:element ref="Definition" maxOccurs="unbounded" minOccurs="0">
                        <xs:annotation>
                            <xs:documentation>The entity official definition</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element name="QuantityRef" type="ReferenceType">
                        <xs:annotation>
                            <xs:documentation>A URI referencing a Quantiy</xs:documentation>
                        </xs:annotation>
                    </xs:element>
                    <xs:element ref="Base"/>
                    <xs:element minOccurs="0" ref="AlternateBase"/>
                </xs:sequence>
                <xs:attribute default="false" name="isDimensionless" type="xs:boolean">
                    <xs:annotation>
                        <xs:documentation>Indicates that this Unit is dimensionless</xs:documentation>
                    </xs:annotation>
                </xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== kulnor/codata-drum/udunits/xml/CodataUnitSystem.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Second level derivation:
    - Units/Unit: Compute BaseSI from Base
    - Units/Unit: Compute @isDimensionless flag
Second level validation:
    - Prefixes/Prefix/@uri: must be unique and match pattern
    - Quantities/Quantity/@uri: must be unique and match pattern
    - Quantities/Quantity/@uri: must be unique and match pattern
    - Units/Unit/BaseSI: Must be consistent with Base
    - Units/Unit/@isDimensionless: Must be consistent with Base / BaseSI
    - Make sure we do not have duplicate name, definition, and similar i18n elements in the same language
Questions:
    - Is base, common, derived, accepted an official categorization of units?
    - Should xml:lamng always be specified, or is English an appropriate default value?
        - What are the official SI languages (english/french?). Are there varitaion like en-us, fr-ca, etc? 
    - Do we need to differentiate between AlternateName as synonym. abbreviation, or other variations? We also have an AlternateSymbol?
    - Should AlternateName carry more information such as source/context/discipline? 
    - Should we support multiple Unit/Definition, or add AlternateDefinition? Shoudl this carry a source/context/discipline?
    - Should we have a format list of Discipline (concept/context)?
    - Where do we really name the singular/plural distinction? Is it only for units?
    - In udunits, why do synonyms have an underscrore (e.g. degree_kelvin)
    - Should we adopt W3C MathML as a standard for mathematcial expressrion? This would probably only weork for XML (e.g. not JSON). What should be ageneric syntax/standard would be recommended?
        - Which syntax should be used for Symbol (e.g. for m^2 where we have a superscript)
    - Should Base also be on the Quantity (not just on Unit)? Not all bases have a Quantity... Does the currennt model allows us to find the SI standard Base for a Quantity?
    - Should we have specialized type for BaseUnit, DerivedUnit, etc. (rather than just Unit)
-->
<UnitSystem xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:/Users/pascal/git-personal/codata-drum/udunits/xml/CodataUnitSystem.xsd">
    <Prefixes> </Prefixes>
    <Quantities>
        <Quantity uri="si:quantity:acceleration">
            <Name>
                <Singular xml:lang="en">acceleration</Singular>
                <Singular xml:lang="fr">accélération</Singular>
            </Name>
        </Quantity>
        <Quantity uri="si:quantity:area">
            <Name>
                <Singular xml:lang="en">area</Singular>
                <Singular xml:lang="fr">aire</Singular>
            </Name>
        </Quantity>
        <Quantity uri="si:quantity:amount">
            <Name>
                <Singular xml:lang="en">amount of substance</Singular>
            </Name>
        </Quantity>
        <Quantity uri="si:quantity:current">
            <Name>
                <Singular xml:lang="en">electrical current</Singular>
                <Singular xml:lang="fr">courant électrique</Singular>
            </Name>
        </Quantity>
        <Quantity uri="si:quantity:length">
            <Name>
                <Singular xml:lang="en">length</Singular>
                <Singular xml:lang="fr">longueur</Singular>
            </Name>
        </Quantity>
        <Quantity uri="si:quantity:luminance">
            <Name>
                <Singular xml:lang="en">luminance</Singular>
                <Singular xml:lang="fr">luminance</Singular>
            </Name>
            <AlternateName>
                <Singular xml:lang="en">luminous intensity</Singular>
                <Singular xml:lang="fr">intensité lumineuse</Singular>
            </AlternateName>
        </Quantity>
        <Quantity uri="si:quantity:mass">
            <Name>
                <Singular xml:lang="en">mass</Singular>
                <Singular xml:lang="fr">masse</Singular>
            </Name>
        </Quantity>
        <Quantity uri="si:quantity:temperature">
            <Name>
                <Singular xml:lang="en">temperature</Singular>
                <Singular xml:lang="fr">température</Singular>
            </Name>
        </Quantity>
        <Quantity uri="si:quantity:time">
            <Name>
                <Singular xml:lang="en">time</Singular>
                <Singular xml:lang="fr">temps</Singular>
            </Name>
        </Quantity>
        <Quantity uri="si:quantity:velocity">
            <Name>
                <Singular xml:lang="en">velocity</Singular>
                <Singular xml:lang="fr">vélocité</Singular>
            </Name>
            <AlternateName>
                <Singular xml:lang="en">speed</Singular>
                <Singular xml:lang="fr">vitesse</Singular>               
            </AlternateName>
        </Quantity>
        <Quantity uri="si:quantity:volume">
            <Name>
                <Singular xml:lang="en">volume</Singular>
                <Singular xml:lang="fr">volume</Singular>
            </Name>
        </Quantity>
    </Quantities>
    <Units>
        <!-- BASE UNITS -->
        <Unit uri="SI:Unit:Base:A">
            <Name>
                <Singular xml:lang="en">ampere</Singular>
                <Singular xml:lang="fr">ampère</Singular>
            </Name>
            <AlternateName>
                <Singular xml:lang="en">amp</Singular>
            </AlternateName>
            <Symbol>A</Symbol>
            <Definition xml:lang="en">The ampere is that constant current which, if maintained in two straight parallel conductors of infinite length, of negligible circular cross-section, and placed 1 meter apart in vacuum, would produce between these conductors a force equal to 2e-7 newton per meter of length.</Definition>
            <QuantityRef>si:quantity:current</QuantityRef>
            <Base>
                <Expression>A</Expression>
                <BaseUnit>
                    <UnitRef>SI:Unit:Base:A</UnitRef>
                    <Exponent>1</Exponent>
                </BaseUnit>
            </Base>
        </Unit>
        <Unit uri="SI:Unit:Base:cd">
            <Name>
                <Singular xml:lang="en">candela</Singular>
            </Name>
            <AlternateName>
                <Singular xml:lang="en">candle</Singular>
                <Plural xml:lang="en">candles</Plural>
            </AlternateName>
            <Symbol>cd</Symbol>
            <Definition xml:lang="en">The candela is the luminous intensity, in a given direction, of a source that emits monochromatic radiation of frequency 540e12 hertz and that has a radiant intensity in that direction of 1/683 watt per steradian.</Definition>
            <QuantityRef>si:quantity:luminance</QuantityRef>
            <Base>
                <Expression>cd</Expression>
                <BaseUnit>
                    <UnitRef>SI:Unit:Base:cd</UnitRef>
                    <Exponent>1</Exponent>
                </BaseUnit>
            </Base>
        </Unit>
        <Unit uri="SI:Unit:Base:K">
            <Name>
                <Singular xml:lang="en">kelvin</Singular>
                <Singular xml:lang="fr">kelvin</Singular>
            </Name>
            <AlternateName>
                <Singular xml:lang="en">degree kelvin</Singular>
                <Plural xml:lang="en">degrees kelvin</Plural>
            </AlternateName>            
            <AlternateName>
                <Singular xml:lang="en">degree kelvin</Singular>
                <Plural xml:lang="en">degrees kelvin</Plural>
            </AlternateName>            
            <AlternateName>
                <Singular xml:lang="en">degree k</Singular>
                <Plural xml:lang="en">degrees k</Plural>
            </AlternateName>            
            <AlternateName>
                <Singular xml:lang="en">deg k</Singular>
                <Plural xml:lang="en">deg k</Plural>
            </AlternateName>            
            <AlternateName>
                <Singular xml:lang="en">degk</Singular>
                <Plural xml:lang="en">degsk</Plural>
            </AlternateName>            
            <Symbol>K</Symbol>
            <AlternateSymbol>&#xB0;K</AlternateSymbol>
            <Definition xml:lang="en">The kelvin, unit of thermodynamic temperature, is the fraction 1/273.16 of the thermodynamic temperature of the triple point of water.</Definition>
            <QuantityRef>si:quantity:temperature</QuantityRef>
            <Base>
                <Expression>K</Expression>
                <BaseUnit>
                    <UnitRef>SI:Unit:Base:K</UnitRef>
                    <Exponent>1</Exponent>
                </BaseUnit>
            </Base>
        </Unit>
        <Unit uri="SI:Unit:Base:kg">
            <Name>
                <Singular xml:lang="en">kilogram</Singular>
                <Singular xml:lang="fr">kilogramme</Singular>
            </Name>
            <Symbol>kg</Symbol>
            <Definition xml:lang="en">The kilogram is the unit of mass; it is equal to the mass of the international prototype of the kilogram.</Definition>
            <QuantityRef>si:quantity:weight</QuantityRef>
            <Base>
                <Expression>kg</Expression>
                <BaseUnit>
                    <UnitRef>SI:Unit:Base:kg</UnitRef>
                    <Exponent>1</Exponent>
                </BaseUnit>
            </Base>
        </Unit>
        <Unit uri="SI:Unit:Base:m">
            <Name>
                <Singular xml:lang="en">meter</Singular>
                <Singular xml:lang="fr">metre</Singular>
            </Name>
            <Symbol>m</Symbol>
            <Definition xml:lang="en">The meter is the length of the path travelled by light in vacuum during a time interval of 1/299 792 458 of a second.</Definition>
            <QuantityRef>si:quantity:length</QuantityRef>
            <Base>
                <Expression>m</Expression>
                <BaseUnit>
